server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests directly to the FastAPI backend
    location /v1/ {
        proxy_pass https://grocery-backend-794191262342.us-central1.run.app/v1/;
        # This line is critical for Cloud Run HTTPS routing:
        proxy_ssl_server_name on;
    }
}