// Name: Paula Tica
// Date: 4/19/2026
// Citation:
// Partially auto-generated by Vite
// Added tailwindcss() when Tailwind was installed
// Added import alias for shadcn based on shadcn docs:
// URL: https://ui.shadcn.com/docs/installation/vite

import path from 'path'
import tailwindcss from '@tailwindcss/vite'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [
    tailwindcss(),
    react(),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
})
