"""remove image_url column

Revision ID: 04c88d92e983
Revises: 018dbdd6bbd3
Create Date: 2026-05-30 12:57:32.359191

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04c88d92e983"
down_revision: Union[str, Sequence[str], None] = "018dbdd6bbd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("food_items", "image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "food_items",
        sa.Column("image_url", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
