"""Add unique constraint between user_id and food_item_id in user_food_items

Revision ID: 0cfb5eb61bba
Revises: 2be068f3ba2f
Create Date: 2026-05-04 15:20:01.988791

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0cfb5eb61bba"
down_revision: Union[str, Sequence[str], None] = "2be068f3ba2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "user_food_id_uc", "user_food_items", ["user_id", "food_item_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_food_id_uc", "user_food_items", type_="unique")
    # ### end Alembic commands ###
