"""add user_id to recipes

Revision ID: 51ab6a0e2152
Revises: ae54dbf86651
Create Date: 2026-05-29 16:19:12.308152

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51ab6a0e2152"
down_revision: Union[str, Sequence[str], None] = "ae54dbf86651"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        None, "recipes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "recipes", type_="foreignkey")
    op.drop_column("recipes", "user_id")
    # ### end Alembic commands ###
