"""updated description length for recipe model to 2000

Revision ID: a6ba130f100a
Revises: ba231fd55e44
Create Date: 2026-05-23 08:41:49.837479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6ba130f100a"
down_revision: Union[str, Sequence[str], None] = "ba231fd55e44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipes",
        "description",
        existing_type=sa.VARCHAR(length=600),
        type_=sa.String(length=2000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipes",
        "description",
        existing_type=sa.String(length=2000),
        type_=sa.VARCHAR(length=600),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
