"""add user_id to recipes

Revision ID: cbdd7eeab229
Revises: b7e2a1f3d890
Create Date: 2026-05-29 19:37:53.065865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbdd7eeab229"
down_revision: Union[str, Sequence[str], None] = "b7e2a1f3d890"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        None, "recipes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "recipes", type_="foreignkey")
    op.drop_column("recipes", "user_id")
    # ### end Alembic commands ###
